version: '2.3'
services:
  notebook:
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
    runtime: nvidia
    network_mode: bridge
    ports:
      - "1500:8888"
    image: phony-jupyter:dev
    command: ['jupyter', 'notebook', '--allow-root', '--NotebookApp.token=""', '--NotebookApp.notebook_dir=/work']
    volumes:
      - ./:/work
